# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Devnet
on: workflow_dispatch

jobs:
  devnet:
    runs-on: ubuntu-latest
    env:
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14.1'
        cache: 'npm'
    - name: Run eslint
      run: |
          npm install -g eslint
          npm install
          npm run lint
    - name: rsync code
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr
        path: ./
        remote_path: ${{ secrets.PATH }}
        remote_host: ${{ secrets.HOST }}
        remote_port: ${{ secrets.PORT }}
        remote_user:  ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.KEY }}
    - name: Restart services
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd ${{ secrets.PATH }}
          bash deploy.sh
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: tomoscan-healthcheck
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON_EMOJI: ':solana:'
        SLACK_MESSAGE: ' ${{ env.COMMIT_MESSAGE }} :rocket: '
        SLACK_USERNAME: solscan-deploy-bot
        SLACK_WEBHOOK: ${{ secrets.SLACK }}

